config/routes.rb
Rails.application.routes.draw do
  Healthcheck.routes(self)
  resources :bands
  resources :events
  resources :artists
  resources :venues
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resource :event_dates, only: [:index]
  resources :articles do
    resources :comments
  end
  root 'event_dates#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user && user.admin?
      can :manage, :all
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :read, :dashboard
    else
      can :read, :all                   # allow everyone to read everything
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :band_memberships, :dependent => :destroy
  has_many :bands, through: :band_memberships

  has_many_attached :images

  rails_admin do
    configure :band_memberships do
      hide
    end
  end
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :band_memberships, :dependent => :destroy
  has_many :events, :dependent => :nullify
  has_many :artists, through: :band_memberships

  has_and_belongs_to_many :genres

  has_many_attached :images

  rails_admin do
    configure :band_memberships do
      hide
    end
  end
end

app/models/band_membership.rb
class BandMembership < ApplicationRecord
  belongs_to :band
  belongs_to :artist
end

app/models/city.rb
class City < ApplicationRecord
  has_many :venues
  has_many :events, through: :venues
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/event.rb
require 'time'
require 'action_view'

class Event < ApplicationRecord
  include ActionView::Helpers::SanitizeHelper

  belongs_to :venue
  belongs_to :band, :optional => true
  has_many_attached :images
  has_many :event_dates, :dependent => :destroy

  has_and_belongs_to_many :genres

  scope :filter_by_name, -> (name) { where name: name}
  scope :filter_by_venue_id, -> (venue_id) { where venue_id: venue_id}
  scope :filter_by_source_url, -> (source_url) { where source_url: source_url}

  def short_description
    if description?
      strip_tags(description).truncate(300)
    else
      ""
    end
  end

  def add_dates(dates)
    if dates
      dates.each do |date|
        event_dates << EventDate.new(date: date[:date])
      end
    end
  end

  def add_images(imgs)
    if imgs
      imgs.each do |image|
        filename = "/tmp/#{image[:filename]}"
        File.open(filename, 'wb') {|f| f.write(Base64.decode64(image[:content]).strip) }
        images.attach(io:  File.open(filename, 'r'), filename: image[:filename])
      end
    end
  end

  def update_dates(wanted_dates)
    wanted_dates = [] if wanted_dates == nil
    wanted_dates = wanted_dates.map {|d| Time.parse(d)}
    event_dates.each do |date|
      if not wanted_dates.include? date.date
        event_dates.delete(date)
      end
    end
    current_dates = event_dates.map{|ed| ed.date}
    wanted_dates.each do |date|
      if not current_dates.include? date
        event_dates << EventDate.new(date: date)
        current_dates << date
      end
    end

    true
  end

  def image
    if images.attached?
      images[0]
    elsif band and band.images.attached?
      band.images[0]
    end
  end
end

app/models/event_date.rb
class EventDate < ApplicationRecord
  belongs_to :event

  def to_s
    return date.to_s
  end

  def month_s
    long = I18n.t('date.month_names')[date.month]
    return long[0..2].upcase
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :bands
  has_and_belongs_to_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_token_authenticatable
  before_create :make_first_user_admin

  def admin?
    return self.administrator
  end

  private
  def make_first_user_admin
    if User.all.length == 0 then
      self.administrator = true
    end
  end
end

app/models/venue.rb
class Venue < ApplicationRecord
  belongs_to :city
  has_many :events, :dependent => :destroy
  has_many_attached :images

  scope :filter_by_name, -> (name) { where name: name}
  scope :filter_by_city, -> (name) {
    city = City.where('lower(name) = ?', name.downcase).first || City.new
    where city_id: city.id
  }

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>music.madrid!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar"  role="navigation" aria-label="main navigation">
    <div class="container is-marginless">
      <div class="navbar-brand">
        <a class="navbar-item" href="/"><h1 class="webtitle">music.madrid</h1></a>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarMenuHeroA">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div id="navbarMenuHeroA" class="navbar-menu">
        <div class="navbar-start">

          <%= active_link_to 'Eventos', events_path, :class_active=> 'is-active', :class => 'navbar-item' %>
          <%= active_link_to 'Clubs', venues_path, :class_active=> 'is-active', :class => 'navbar-item' %>
          <%= active_link_to 'Grupos', bands_path, :class_active=> 'is-active', :class => 'navbar-item' %>
          <!-- TODO: artistas -->
          <!-- TODO: escuelas -->
        </div>
        <div class="navbar-end">

          <div class="navbar-item has-dropdown is-hoverable">
            <div class="navbar-link">
              Account
            </div>
            <div class="navbar-dropdown">

                <% if user_signed_in? %>
                  <a class="navbar-item">Logged in as <%= current_user.email %>.</a>
                        <% if can? :access, :rails_admin %>
                          <%= link_to 'Consola administrativa', rails_admin_path, :class => 'navbar-item' %>
                        <% end %>
                        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-item' %>
                        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-item'  %>

                <% else %>

                        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-item'  %>
                        <%= link_to "Login", new_user_session_path, :class => 'navbar-item'  %>
                <% end %>

            </div>
          </div>
        </div>
      </div>

    </div>
  </nav>

  <!--<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
      <-% for page in @page.ancestors.reverse %>
        <li><-%= active_link_to h(page.name), page, :class_active=> 'is-active' %> </li>
      <-% end %>
    </ul>
  </nav>
  -->



  <section class="container is-marginless">
    <div class="container is-fluid">
      <% if alert %>
      <article class="message is-danger">
        <div class="message-header"><p>Alert</p></div>
        <div class="message-body"><%= alert %>></div>
      </article>
     <% end %>
      <% if notice %>
        <article class="message is-info">
          <div class="message-header"><p>Message</p></div>
          <div class="message-body"><%= notice %></div>
        </article>
      <% end %>
    </div>
    <div class="container is-fluid  ">
      <%= yield %>
    </div>
  </section>
  </body>
</html>